version: '2'
services:
  api:
    build:
      dockerfile: docker/FalconDockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - FALCON_SETTINGS_MODULE=wadoym.settings.docker

    links:

      - mongodb
      - redisdb

  mongodb:
    image: mongo
    ports:
      - "47017:27017"

  redisdb:
    image: redis
    ports:
      - "4379:6379"

